name: Keep Render Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Enables a manual run button in the UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -s -f -m 30 "https://perfusion.shreykansara.dev/reports" || echo "Ping failed or timed out"
